config/routes.rb
Enciteopedia::Application.routes.draw do
resources 'veditors'
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
   get "editors/index"
   get "editors/new"
   get "editors/create"
   get "editors/update"
   get "home/top"
   get "editors/destroy"
   get "veditors/show"
   get "veditors/index"
   get "veditors/new"
  post "veditors/approve"

get "veditors/like"
get "veditors/unlike"
   get "veditors/create"
   get "veditors/update"
   get "veditors/destroy"
   get "veditors/show"
   get "misc/policy"
   get "misc/community"
   get "home/homepage"
   get "home/articles"
   get "home/index"
   get "home/show"
   get "home/new"
   get "home/policy"
   get "home/community"
   get "articles/artlist"
   get "articles/index"
   get "articles/new"
   get "articles/show"
get "articles/update"
get "articles/destroy"
get "articles/create"

resources 'home'  do
member do
	get 'top'
end
end
resources 'articles'
resources 'veditors'do
 member do
	get 'like'
	get 'unlike'
	get 'approve'
end
end
resources :editors do
 member do
	get 'like'
	get 'unlike'
end
end
resources 'sessions'

  match '/signup',:to => 'users#index'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   respond_to :html
   helper_method :sort_column, :sort_direction
  # GET /articles
  # GET /articles.json
  def index
  @editors = Editor.all
  @vote = Vote.all
  @articles = Article.order(sort_column + " " + sort_direction)
  @aeor = Aeor.find_all_by_editor_id(session[:remember_token]).uniq
  @rarticles = Array.new
  @aeor.each do |a|
   @rarticles.push( Article.find_by_id(a.article_id))
  end
  end
    def top
  @items = Editor.tally()
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @article.hits += 1
    @article.save
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    @article.hits == 0
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    @article.hits = 0
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
private  
  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "hits"
  end

  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :aName %>
  </div>
   <div class="field">
    <%= f.label :Category %><br />
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/_form2.html.erb
<%= search_form_for @search do |f| %>

  <%= f.label :Name %>
  <%= f.text_field :aName_cont %>
<br/>
  <%= f.label :Category %>
  <%= f.collection_select :Category_cont, Article.all, :id, :Category, :include_blank => true %>
<br/>
  <%= f.label :content_cont %>
  <%= f.text_field :content_cont %>

  <%= f.submit %>
<% end %>

<p>

</p>

app/views/home/articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnCITEopedia</title>
<%= stylesheet_link_tag '/stylesheets/depot.css', :media => :screen %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= form_for articles_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Article", :name => nil %>
  </p>
<% end %>


<table id="nqa">
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Hits</th>
    
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.aName %></td>
     <td><%= article.Category %></td>
    <td><%= article.hits %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= button_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>



</body>
</html>

app/views/home/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/home/homepage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnCITEopedia</title>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>

<table id="nq">
  <tr>
    <th>Article Name</th>
    <th>Content</th>
    <th>Hits</th>
    <th>Images</th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.aName %></td>
    <td><%= article.content %></td>
    <td><%= article.hits %></td>
<td><%= article.images %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= button_to 'Destroy', question, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

</table>




</body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnCITEopedia</title>
<%= stylesheet_link_tag '/stylesheets/depot.css', :media => :screen %>
<%= stylesheet_link_tag    'scaffold', :media => :screen %> 
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice]%>

<% if session[:remember_token] == nil%>
<%= form_for(:session, :url => sessions_path) do |f| %>
<%= f.label :email%>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit "login" %>
<%end%>
<%end%>

<h1><%= link_to 'Request to become editor', :controller => :veditors, :action => :index  %></h1>


<table id="nqa">
  <tr>
    <th><%= sortable "aName" %></th>
    <th><%= sortable "Category" %></th>
    <th><%= sortable "hits" %></th>

    
    <th></th>
    <th></th>
  </tr>

<h1> Top Articles <h1>

<% @articles.limit(5).each do |article| %>
  <tr>
    <td><%= article.aName %></td>
     <td><%= article.Category %></td>
    <td><%= article.hits %></td>
    <td><%= link_to 'Show', article %></td>
    
	
<% if session[:remember_token] != nil%> 
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
<% if session[:editor_id] == 11 %>
    <td><%= button_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
<%end%>
  <%end%>  
  </tr>
<% end %>
</table>
<br/>
<br/>
<br/>


<h1><%= link_to 'Top Editors', :controller => :home, :action => :top  %></h1>

<br/>
<br/>
<br/>


<table>
  <tr>
    <th><%= sortable "aName" %></th>
    <th><%= sortable "Category" %></th>
    <th><%= sortable "hits" %></th>

    
    <th></th>
    <th></th>
  </tr>

<h1> Your Edits <h1>

<% @rarticles.each do |article| %>
  <tr>
    <td><%= article.aName %></td>
     <td><%= article.Category %></td>
    <td><%= article.hits %></td>
    <td><%= link_to 'Show', article %></td>
    
	
<% if session[:remember_token] != nil%> 
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
<% if session[:editor_id] == 11 %>
    <td><%= button_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
<%end%>
  <%end%>  
  </tr>
<% end %>
</table>



</body>
</html>

app/views/home/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/home/show.html.erb
<p>
  <b>Aname:</b>
  <%= @article.aName %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<p>
  <b>Hits:</b>
  <%= @article.hits %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@article.avatar.url).html_safe %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
<head>

<table id="nqa">
  <tr>
    <th>Name</th>
    <th>Thumbs<th/>
    
    <th></th>
    <th></th>
  </tr>

<% @items.each do |editor| %>
  <tr>
	<td><%= editor.name %></td>
     <td><%= editor.plusminus %></td>
<%end%>

</body>
</html>