config/routes.rb
Enciteopedia::Application.routes.draw do
resources 'veditors'
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
   get "editors/index"
   get "editors/new"
   get "editors/create"
   get "editors/update"
   get "home/top"
   get "editors/destroy"
   get "veditors/show"
   get "veditors/index"
   get "veditors/new"
  post "veditors/approve"

get "veditors/like"
get "veditors/unlike"
   get "veditors/create"
   get "veditors/update"
   get "veditors/destroy"
   get "veditors/show"
   get "misc/policy"
   get "misc/community"
   get "home/homepage"
   get "home/articles"
   get "home/index"
   get "home/show"
   get "home/new"
   get "home/policy"
   get "home/community"
   get "articles/artlist"
   get "articles/index"
   get "articles/new"
   get "articles/show"
get "articles/update"
get "articles/destroy"
get "articles/create"

resources 'home'  do
member do
	get 'top'
end
end
resources 'articles'
resources 'veditors'do
 member do
	get 'like'
	get 'unlike'
	get 'approve'
end
end
resources :editors do
 member do
	get 'like'
	get 'unlike'
end
end
resources 'sessions'

  match '/signup',:to => 'users#index'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'

end

app/models/editor.rb
require 'digest'
class Editor < ActiveRecord::Base
acts_as_voter
acts_as_voteable
has_many :Hists
has_many :Editors, :through => :History
has_many :Aeors
has_many :Articles, :through => :Aeor

attr_accessor :password	
attr_accessible :name, :email, :password, :password_confirmation, :thumbs
validates :name, :presence => true, :length => {:maximum => 50}
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, :presence =>true, :format => {:with=>email_regex},:uniqueness => {:case_sensitive => false}
validates :password, :presence => true, :confirmation=>true, :length=>{:within => 6..40}
before_save :encrypt_password
private
=begin
	def encrypt_password
		self.encrypted_password = encrypt(password)
	end
=end
	def encrypt
		string
	end
	public
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	def encrypt_password
		self.salt = make_salt unless has_password?(password)
		self.encrypted_password = encrypt(password)
	end
	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end
	def make_salt
		secure_hash("#{Time.now.utc}--#{password}")
	end
	def secure_hash(string)
		Digest::SHA2.hexdigest(string)
	end
	def self.authenticate(email,submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.current
    		Thread.current[:editor]
  	end
  		def self.current=(editor)
    	Thread.current[:editor] = editor
  end



end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  # GET /articles
  # GET /articles.json
helper_method :sort_column, :sort_direction

  def index
  @editors = Editor.all
  @thumbs = Hist.where("Editor_id = ?", params[:id])
  
   end
  def like
	@article = Hist.find(params[:id])
        @hist = Hist.find(params[:id])
	@voter = Editor.find(session[:remember_token])
        @votee = Editor.find_by_id(Hist.select(:editor_id).where("Article_id = ?", @article))
  		@voter.vote_for(@votee)
  		redirect_to editors_path, :notice => "you now like this edit"
  end

  def unlike
	@a = Hist.find(params[:id])
        @hist = Hist.find(params[:id])
	@voter = Editor.find(session[:remember_token])
        @votee = Editor.find_by_id(Hist.select(:editor_id).where("Id = ?", @a))
  		@voter.vote_against(@votee)
  		redirect_to editors_path, :notice => "you now like this edit"
  end
 


  # GET /articles/1
  # GET /articles/1.json
  def show
    @editor = Editor.find(params[:id])
    @aeor = Aeor.find_all_by_editor_id(params[:id])
    @aarticles = Array.new
    @aeor.each do |a|
    @aarticles.push( Article.find_by_id(a.article_id))
   end
   
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @editor = Editor.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @editor }
    end
  end

  # GET /articles/1/edit
  def edit
    @editor = Editor.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @editor = Editor.new(params[:editor])
    respond_to do |format|
      if @editor.save
        format.html { redirect_to @editor, notice: 'Article was successfully created.' }
        format.json { render json: @editor, status: :created, location: @editor }
      else
        format.html { render action: "new" }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @editor = Editor.find(params[:id])

    respond_to do |format|
      if @editor.update_attributes(params[:editor])
        format.html { redirect_to @editor, notice: 'Editor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @editor = Editor.find(params[:id])
    @editor.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
  helper_method :current_editor #make this method available in views
private  
  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "hits"
  end

  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/_form.html.erb
<br />
<br />
<br />
<br />
<h1>Please enter the following information</h1>
<%= form_for (@editor) do |f| %>

<%= f.label :name %><br/>
<%= f.text_field :name %><br />

<%= f.label :email%><br/>
<%= f.text_field :email %><br />

<%= f.label :password %><br/>
<%= f.password_field :password %><br />
<%= f.label :passwordConfirm %><br/>
<%= f.password_field :password_confirmation %><br />

<%= f.submit "login" %>
<% end %>

app/views/editors/create.html.erb
<br />
<br />
<br />
<br />
<h1>Please enter the following information</h1>
<%= form_for @editor, :action=> :create do |f| %>

<%= f.label :name %><br/>
<%= f.text_field :name %><br />

<%= f.label :email%><br/>
<%= f.text_field :email %><br />

<%= f.label :password %><br/>
<%= f.password_field :password %><br />
<%= f.label :passwordConfirm %><br/>
<%= f.password_field :password_confirmation %><br />

<%= f.submit "login" %>
<% end %>

app/views/editors/destroy.html.erb
<h1>Editors#destroy</h1>
<p>Find me in app/views/editors/destroy.html.erb</p>

app/views/editors/edit.html.erb
<h1>Editing editor</h1>

<%= render 'form' %>

<%= link_to 'Show', @editor %> |
<%= link_to 'Back', editors_path %>

app/views/editors/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnCITEopedia</title>
<%= stylesheet_link_tag '/stylesheets/depot.css', :media => :screen %>
<%= stylesheet_link_tag    'scaffold', :media => :screen %> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice]%>
<table id="nqa">
  <tr>
    <th>Name</th>
    <th>email</th>
    <th>Thumbs<th/>
    
    <th></th>
    <th></th>
  </tr>

<% @editors.each do |editor| %>
  <tr>

    <td><%= editor.name %></td>
     <td><%= editor.email %></td>
     <td><%= editor.plusminus %></td>
     

<td><%= link_to 'Show', editor %></td>
<% if session[:remember_token] != nil%> 
   

<td><%= link_to 'Edit', edit_editor_path(editor) %></td>
<% if session[:editor_id] == 11 %>
    
    <td><%= button_to 'Destroy', editor, confirm: 'Are you sure?', method: :delete %></td>
<% end %>
<% end %>
  </tr>

<% end %>
</table>


</body>
</html>

app/views/editors/new.html.erb
<h1>New Editor</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/editors/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnCITEopedia</title>
<%= stylesheet_link_tag '/stylesheets/depot.css', :media => :screen %>
<%= stylesheet_link_tag    'scaffold', :media => :screen %> 
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tags %>
</head>
<body>

<p>
  <b>Name:</b>
  <%= @editor.name %>
</p>

<p>
  <b>Email:</b>
  <%= @editor.email %>
</p>


<table>
  <tr>
   <th>aName</th>
    <th>Category</th>
    <th>hits</th>

    
    <th></th>
    <th></th>
  </tr>

<h1> Edits by <%=@editor.name%> <h1>

<% @aarticles.each do |article| %>
  <tr>
    <td><%= article.aName %></td>
     <td><%= article.Category %></td>
    <td><%= article.hits %></td>
    <td><%= link_to 'Show', article %></td>
    
	
<% if session[:remember_token] != nil%> 
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
<% if session[:editor_id] == 11 %>
    <td><%= button_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
<%end%>
  <%end%>  
  </tr>
<% end %>
</table>

<% if session[:editor_id] == 11 %>
<%= link_to 'Edit', edit_editor_path(@editor) %> |
<% end %>
<%= link_to 'Back', editors_path %>

</body>
</html>

app/views/editors/top.html.erb
<!DOCTYPE html>
<html>
<head>

<table id="nqa">
  <tr>
    <th>Name</th>
    <th>Thumbs<th/>
    
    <th></th>
    <th></th>
  </tr>

<% @items.each do |editor| %>
  <tr>
	<td><%= editor.name %></td>
     <td><%= editor.plusminus %></td>
<%end%>

</body>
</html>

app/views/editors/update.html.erb
<h1>Editors#update</h1>
<p>Find me in app/views/editors/update.html.erb</p>