config/routes.rb
Enciteopedia::Application.routes.draw do
resources 'veditors'
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
   get "editors/index"
   get "editors/new"
   get "editors/create"
   get "editors/update"
   get "home/top"
   get "editors/destroy"
   get "veditors/show"
   get "veditors/index"
   get "veditors/new"
  post "veditors/approve"

get "veditors/like"
get "veditors/unlike"
   get "veditors/create"
   get "veditors/update"
   get "veditors/destroy"
   get "veditors/show"
   get "misc/policy"
   get "misc/community"
   get "home/homepage"
   get "home/articles"
   get "home/index"
   get "home/show"
   get "home/new"
   get "home/policy"
   get "home/community"
   get "articles/artlist"
   get "articles/index"
   get "articles/new"
   get "articles/show"
get "articles/update"
get "articles/destroy"
get "articles/create"

resources 'home'  do
member do
	get 'top'
end
end
resources 'articles'
resources 'veditors'do
 member do
	get 'like'
	get 'unlike'
	get 'approve'
end
end
resources :editors do
 member do
	get 'like'
	get 'unlike'
end
end
resources 'sessions'

  match '/signup',:to => 'users#index'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'

end

app/models/veditor.rb
class Veditor < ActiveRecord::Base
acts_as_voteable
attr_accessor :password
attr_accessible :name, :email, :password, :password_confirmation
end

app/controllers/veditors_controller.rb
class VeditorsController < ApplicationController
  # GET /arteditors
  # GET /arteditors.json
  def index
    @veditors = Veditor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @veditors }
    end
  end

   def like
	@voter = Editor.find(session[:remember_token])
        @votee = Veditor.find(params[:vid])
        if @voter.voted_for?(@votee) == false
  		@voter.vote_for(@votee)
  		redirect_to veditors_path, :notice => "you have voted for this veditor"
		
	else 
		redirect_to veditors_path, :notice => "you have already voted"
  end
  end
     def unlike
	@voter = Editor.find(session[:remember_token])
        @votee = Veditor.find(params[:vid])
        if @voter.voted_for?(@votee) == false
  		@voter.vote_against(@votee)
  		redirect_to veditors_path, :notice => "you have voted against this veditor"
		else 
		redirect_to veditors_path, :notice => "you have already voted"
        
  end
  end

  # GET /arteditors/1
  # GET /arteditors/1.json
  def show
    @veditor = Veditor.find(params[:vid])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @veditor }
    end
  end

  # GET /arteditors/new
  # GET /arteditors/new.json
  def new
    @veditor = Veditor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @veditor }
    end
  end

  # GET /arteditors/1/edit
  def edit
    @veditor = Veditor.find(params[:vid])
  end

  # POST /arteditors
  # POST /arteditors.json
  def create
    @veditor = Veditor.new(params[:veditor])

    respond_to do |format|
      if @veditor.save
        format.html { redirect_to @veditor, notice: 'Arteditor was successfully created.' }
        format.json { render json: @veditor, status: :created, location: @veditor }
      else
        format.html { render action: "new" }
        format.json { render json: @veditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arteditors/1
  # PUT /arteditors/1.json
  def update
    @veditor = Veditor.find(params[:vid])

    respond_to do |format|
      if @veditor.update_attributes(params[:veditor])
        format.html { redirect_to @veditor, notice: 'Arteditor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @veditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arteditors/1
  # DELETE /arteditors/1.json
  def destroy
    @veditor = Veditor.find(params[:id])
    @veditor.destroy

    respond_to do |format|
      format.html { redirect_to veditors_url }
      format.json { head :ok }
    end
  end

def approve
    @veditor = Veditor.find(params[:vid])
    @editor = Editor.new(:name => @veditor.name, :email =>@veditor.email, :password => @veditor.name)
    @editor.save
    @veditor.destroy


  end
end

app/views/veditors/_form.html.erb
<br />
<br />
<br />
<br />
<h1>Please enter the following information</h1>
<%= form_for (@veditor) do |f| %>

<%= f.label :name %><br/>
<%= f.text_field :name %><br />

<%= f.label :email%><br/>
<%= f.text_field :email %><br />

<%= f.label :password %><br/>
<%= f.password_field :password %><br />

<%= f.label :description %><br/>
<%= f.text_area :p %><br />


<%= f.submit "login" %>
<% end %>

app/views/veditors/approve.html.erb
APPROVED!

app/views/veditors/edit.html.erb
<h1>Editing veditor</h1>

<%= render 'form' %>

<%= link_to 'Show', @veditor %> |
<%= link_to 'Back', veditors_path %>

app/views/veditors/index.html.erb
<h1>Listing veditors</h1>
<%= flash[:notice]%>
<table>
  <tr>
    <th>name</th>
    <th>email</th>
    <th>net vote count</th>
  </tr>

<% @veditors.each do |veditor| %>
  <tr>

 <td><%= veditor.name %></td>
     <td><%= veditor.email %></td>
<td><%= veditor.plusminus %></td>
    <td><%= link_to 'Show', veditor, :vid=>veditor.id %></td>
    <td><%= link_to 'Edit', edit_veditor_path(veditor) %></td>
    
<% if session[:editor_id] == 11 %>
    <td><%= button_to 'Destroy', veditor, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= button_to 'Approve', :controller => :veditors, :action => :approve, :vid=>veditor.id%></td>

<%end%>
<td><%= link_to 'Thumbs Up', :controller => :veditors, :action => :like, :vid => veditor.id %></td> |
    <td><%= link_to 'Thumbs Down', :controller => :veditors, :action => :unlike , :vid => veditor.id %></td> |

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Veditor', new_veditor_path %>

app/views/veditors/new.html.erb
<h1>New arteditor</h1>

<%= render 'form' %>

<%= link_to 'Back', veditors_path %>

app/views/veditors/show.html.erb
<%= link_to 'Edit', edit_veditor_path(@veditor) %> |
<%= link_to 'Back', veditors_path %>